GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "testing create new todo 4"    
}

###

POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "imtheseconduser",
    "password": "khangpro3107"
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "imtheseconduser",
    "password": "khangpro3107"
}

###

DELETE http://localhost:3001/todo/61f785ec259011925a3776ce

###

PATCH http://localhost:3001/todo/61f785ec259011925a3776ce
Content-Type: application/json

{
    "completed": false
}